/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnxietyTherapyRouteImport } from './routes/anxiety-therapy'
import { Route as IndexRouteImport } from './routes/index'

const AnxietyTherapyRoute = AnxietyTherapyRouteImport.update({
  id: '/anxiety-therapy',
  path: '/anxiety-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anxiety-therapy': typeof AnxietyTherapyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anxiety-therapy': typeof AnxietyTherapyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anxiety-therapy': typeof AnxietyTherapyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anxiety-therapy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anxiety-therapy'
  id: '__root__' | '/' | '/anxiety-therapy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnxietyTherapyRoute: typeof AnxietyTherapyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anxiety-therapy': {
      id: '/anxiety-therapy'
      path: '/anxiety-therapy'
      fullPath: '/anxiety-therapy'
      preLoaderRoute: typeof AnxietyTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnxietyTherapyRoute: AnxietyTherapyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
